// <auto-generated />
namespace HotelManagemant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class roombookingmanytomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roombookingmanytomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050147274_room-booking-many-to-many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
